<?xml version="1.0" encoding="utf-8"?>

<Project Sdk="Dalamud.NET.Sdk/15.0.0">
    <PropertyGroup>
        <Version>0.5.0.1</Version>
        <Description>Yet Another FFXIV Roulette Recorder Written in Fully CSharp.</Description>
        <PackageProjectUrl>https://github.com/StarHeartHunt/RouletteRecorder.Dalamud</PackageProjectUrl>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="CsvHelper" Version="33.1.0" />
    </ItemGroup>

    <ItemGroup>
        <EmbeddedResource Include="Resources\zh_CN.json">
            <CopyToOutputDirectory>Never</CopyToOutputDirectory>
        </EmbeddedResource>
    </ItemGroup>
</Project>
