<?xml version="1.0" encoding="utf-8"?>

<Project Sdk="Dalamud.NET.Sdk/15.0.0">
    <PropertyGroup>
        <Version>1.0.7.0</Version>
        <AssemblyVersion>1.0.7.0</AssemblyVersion>
        <FileVersion>1.0.7.0</FileVersion>
        <InformationalVersion>1.0.7.0</InformationalVersion>
        <Name>日随伴侣</Name>
        <Punchline>自动记录每日随机任务，包括指导者随机任务。&#x0A;&#x0A;Auto record your daily roulettes including mentor roulettes.</Punchline>
        <Description>帮助你记录每日随机任务、导出报告，并实时同步到 DungeonLogger。&#x0A;&#x0A;Help you to record your daily roulettes, export reports, and sync with DungeonLogger in real time.</Description>
        <Tags>随机任务;指导者;roulette;mentor;plugin</Tags>
        <PackageProjectUrl>https://github.com/anmili2022/RouletteRecorder.Dalamud</PackageProjectUrl>
        <AssemblyName>RouletteBuddy</AssemblyName>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <IsPackable>false</IsPackable>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <OutputPath>$(MSBuildThisFileDirectory)..\output\</OutputPath>
        <DalamudLibPath Condition="Exists('$(AppData)\XIVLauncherCN\addon\Hooks\dev\Dalamud.dll')">$(AppData)\XIVLauncherCN\addon\Hooks\dev\</DalamudLibPath>
        <DalamudLibPath Condition="'$(DalamudLibPath)'=='' And Exists('$(AppData)\XIVLauncher\addon\Hooks\dev\Dalamud.dll')">$(AppData)\XIVLauncher\addon\Hooks\dev\</DalamudLibPath>
        <AssemblySearchPaths>$(DalamudLibPath);$(AssemblySearchPaths)</AssemblySearchPaths>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="CsvHelper" Version="33.1.0" />
        <PackageReference Include="Vortice.Direct3D11" Version="3.8.3" />
        <PackageReference Include="Vortice.DXGI" Version="3.8.3" />
    </ItemGroup>

    <ItemGroup>
        <EmbeddedResource Include="Resources\zh_CN.json">
            <CopyToOutputDirectory>Never</CopyToOutputDirectory>
        </EmbeddedResource>
        <EmbeddedResource Include="Shaders\AlphaFix.cso" />
        <EmbeddedResource Include="Shaders\HBlur.cso" />
        <EmbeddedResource Include="Shaders\VBlur.cso" />
    </ItemGroup>

    <Target Name="LocalizeOutputManifestInternalName" AfterTargets="_CheckContainersPackage" Condition="Exists('$(OutputPath)$(AssemblyName).json')">
        <Exec Command="powershell -NoProfile -ExecutionPolicy Bypass -File &quot;$(MSBuildProjectDirectory)\Build\LocalizeOutputManifest.ps1&quot; -ManifestPath &quot;$(OutputPath)$(AssemblyName).json&quot; -PackageZipPath &quot;$(OutputPath)$(AssemblyName)\latest.zip&quot;" />
    </Target>
</Project>

